# Generated by Django 5.1.5 on 2025-01-18 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_author_year_of_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='year_of_death',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
